@startuml
'https://plantuml.com/sequence-diagram

autonumber stop
group Protocol
    Publisher <- Tnsd : Alive(Hash Token)
    Publisher <- Publisher : Check(Hash Token)
    Publisher -> Tnsd : Answer(Hash Token)
    note left
        정상인 경우
    end note
end

group Protocol
    Publisher -> Tnsd : Notify(Topic)
    note left
        비정상 경우
    end note

    Tnsd -> Subsriber : Change(A Publisher)

    group TCP/IP
        Subsriber -> Publisher : Connect to A Publisher
    end

end
group Protocol
    Tnsd -> Subsriber : Alive
    Tnsd <- Subsriber : Answer
end
@enduml