@startuml
'https://plantuml.com/sequence-diagram

collections Subscriber as Subscriber

autonumber
group TCP/IP
    "A Publisher" -> Tnsd : connect
end
group protocol
    "A Publisher" -> Tnsd : Notify(Topic)
    Tnsd -> Subscriber : Change(A Publisher)
end

autonumber stop
group TCP/IP
    "A Publisher" <-- Subscriber : Connect to A Publisher
    "A Publisher" <-- Subscriber : Connect to A Publisher
    "A Publisher" <-- Subscriber : ..
end

autonumber stop
group protocol
    Subscriber <-- "A Publisher" : Publish(Stream)
    Subscriber <-- "A Publisher" : ..
    Subscriber <-- "A Publisher" : ..
end

@enduml
